# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 04:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20161206_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
